const $=s=>document.querySelector(s);let socket,state,myId,joinInfo,retryCount=0,retryTimer,toastTimer,connected=false,joinFailed=false;
let setup={suspect:{adjective:null,noun:null},tool:{adjective:null,noun:null},motive:{adjective:null,noun:null}},extra={tileType:null,word:null,zone:null};
const zones={suspect:'용의자',tool:'범행 도구',motive:'살해 동기'};
function newToken(){const bytes=crypto.getRandomValues(new Uint8Array(32));return [...bytes].map(x=>x.toString(16).padStart(2,'0')).join('')}
function send(m){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(m))}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1900)}
function connect(mode='online',resume=false){clearTimeout(retryTimer);retryCount=0;joinFailed=false;if(!resume){const code=mode==='ai'?'':$('#code').value.trim().toUpperCase();let token=code?localStorage.getItem(`dm-token:${code}`):null;token||=newToken();joinInfo={type:mode==='ai'?'solo':'join',mode,name:$('#name').value.trim()||'수사관',code,resumeToken:token}}openSocket()}
function openSocket(){if(!joinInfo)return;socket=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/room`);socket.onopen=()=>send(joinInfo);socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='welcome'){myId=m.id;connected=true;joinFailed=false;joinInfo.code=m.code;joinInfo.mode=m.mode;localStorage.setItem(`dm-token:${m.code}`,joinInfo.resumeToken);localStorage.setItem('dm-last-session',JSON.stringify({mode:m.mode,code:m.code,name:joinInfo.name,token:joinInfo.resumeToken}));$('#lobby').classList.add('hidden');$('#game').classList.remove('hidden')}if(m.type==='state'){state=m.state;render()}if(m.type==='left'){const oldCode=joinInfo?.code;joinInfo=null;state=null;connected=false;retryCount=0;clearTimeout(retryTimer);if(oldCode){localStorage.removeItem(`dm-token:${oldCode}`);$('#code').value=''}localStorage.removeItem('dm-last-session');$('#game').classList.add('hidden');$('#lobby').classList.remove('hidden');$('#messages').innerHTML='<div class="chat-note">소설가가 남긴 힌트에 대해 토론하세요.</div>';toast('방에서 나왔습니다.')}if(m.type==='notice'){addMessage(null,m.message,true);toast(m.message)}if(m.type==='chat')addMessage(m.name,m.text);if(m.type==='error'){const e=$('#join-error');e.textContent=m.message;if(!connected){joinFailed=true;clearTimeout(retryTimer);socket.close(1000,'join failed')}}};socket.onerror=()=>{if(!connected)$('#join-error').textContent='서버 연결을 확인하고 다시 시도해 주세요.'};socket.onclose=()=>{if(!joinInfo)return;connected=false;if(joinFailed)return;if(retryCount<12){retryCount++;const wait=Math.min(12000,700*2**Math.min(retryCount-1,4));toast(`연결이 끊겼어요. ${Math.ceil(wait/1000)}초 후 다시 연결합니다.`);retryTimer=setTimeout(openSocket,wait)}else toast('재접속에 실패했습니다. 연결을 확인하고 새로고침해 주세요.')}}
function addMessage(name,text,notice=false){const box=$('#messages');box.querySelector('.chat-note')?.remove();const row=document.createElement('div');row.className=`message${notice?' notice':''}`;if(notice)row.textContent=text;else{const b=document.createElement('b');b.textContent=name;const span=document.createElement('span');span.textContent=` ${text}`;row.append(b,span)}box.append(row);box.scrollTop=box.scrollHeight}
function render(){if(!state)return;$('#room-code').textContent=state.code;$('#player-count').textContent=`${state.players.length} / 6`;
 $('#players').replaceChildren(...state.players.map(p=>{const row=document.createElement('div');row.className='player-row';const av=document.createElement('span');av.className='avatar';av.textContent=p.role==='writer'?'✍️':'🕵️';const name=document.createElement('span');name.textContent=p.name;const tag=document.createElement('span');tag.className=`player-tag ${p.connected?'is-connected':'is-away'}`;tag.textContent=p.role==='writer'?'소설가':p.connected?'수사관':'재접속 대기';row.append(av,name,tag);return row}));
 const g=state.game;if(!g){const aiLobby=state.mode==='ai',minPlayers=aiLobby?1:2;$('#phase-label').textContent=aiLobby?'AI 소설가 대기':'참가 대기';$('#lives').textContent='방장이 시작할 때까지 대기';$('#role-label').textContent='수사관';$('#role-pill').textContent=state.owner?'방장':'참가자';$('#round-label').textContent='GAME LOBBY';$('#turn-title').textContent=aiLobby?'AI 소설가 방 대기실':'친구들을 기다리고 있어요';$('#game-subtitle').textContent=aiLobby?'AI가 소설가 역할을 맡습니다. 방 코드를 공유해 함께 수사하세요.':'방 코드를 공유하세요. 2~6명이 모이면 시작할 수 있습니다.';$('#waiting-description').textContent=aiLobby?'AI가 힌트를 준비합니다. 코드로 친구를 초대하고, 방장이 시작하면 함께 추리하세요.':'방 코드를 친구들과 공유하세요. 2~6명이 모이면 방장이 사건을 시작합니다.';$('#status-note').textContent='';$('#waiting-panel').classList.remove('hidden');$('#start-game').disabled=!state.owner||state.players.length<minPlayers;$('#start-game').innerHTML=aiLobby?'AI 사건 시작 <span>→</span>':'사건 시작 <span>→</span>';$('#start-help').textContent=state.owner?(state.players.length<minPlayers?'참가자를 기다리거나 지금 AI 사건을 시작할 수 있어요.':'준비가 끝나면 사건을 시작하세요.'):'방장이 게임을 시작하면 역할이 배정됩니다.';$('#start-game').classList.toggle('hidden',!state.owner);$('#writer-panel').classList.add('hidden');$('#add-hint-panel').classList.add('hidden');$('#zones').replaceChildren();$('#action-row').classList.add('hidden');$('#final-panel').classList.add('hidden');$('#result-panel').classList.add('hidden');$('#restart').classList.add('hidden');$('#chat-form').classList.add('hidden');return}
 const writer=g.privateRole==='writer',ai=g.privateRole==='ai';$('#waiting-panel').classList.add('hidden');$('#phase-label').textContent=({setup:'초기 힌트',eliminate:`${g.round}라운드 추리`,addHint:`${g.round}라운드 힌트`,final:'최종 추리',result:'사건 종료'})[g.phase]||'진행 중';$('#lives').textContent=`추리 타일 ${'● '.repeat(g.lives)}${'○ '.repeat(4-g.lives)}`;$('#round-label').textContent=`ROUND ${String(g.round).padStart(2,'0')} / 03`;$('#role-label').textContent=writer?'소설가':ai?'AI 소설가':'수사관';$('#role-pill').textContent=writer?'소설가 시점':ai?'AI 소설가':'수사관 시점';const secretPanel=$('#writer-solution'),privateAnswers=g.privateData?.secret;secretPanel.classList.toggle('hidden',!writer);if(writer&&privateAnswers)for(const[zone,id]of Object.entries(privateAnswers)){const answer=g.cards[zone].find(card=>card.id===id);$(`#writer-answer-${zone}`).textContent=answer?.name||'확인 불가'}$('#turn-title').textContent=({setup:'초기 힌트를 배치하세요',eliminate:'오답 카드 6장을 제외하세요',addHint:'소설가의 추가 힌트',final:'정답 카드 3장을 남기세요',result:g.message?.includes('정답입니다')?'사건 해결':'사건 종료'})[g.phase]||'';$('#game-subtitle').textContent=g.phase==='setup'?(writer?'각 영역에 형용사와 명사를 하나씩 놓습니다.':'소설가가 초기 힌트를 준비하고 있습니다.'):g.phase==='eliminate'?'정답이 아닌 카드 6장을 토론해 함께 제외하세요.':g.phase==='addHint'?(writer?'보유 타일 중 하나를 골라 원하는 영역에 추가하세요.':'소설가가 다음 힌트를 준비하고 있습니다.'):'세 영역의 힌트와 남은 카드를 살펴보세요.';$('#status-note').textContent=g.message||'';
 $('#writer-panel').classList.toggle('hidden',!(writer&&g.phase==='setup'));$('#add-hint-panel').classList.toggle('hidden',!(writer&&g.phase==='addHint'));$('#action-row').classList.toggle('hidden',g.phase!=='eliminate'||writer);$('#final-panel').classList.toggle('hidden',g.phase!=='final'||writer);$('#result-panel').classList.toggle('hidden',g.phase!=='result');$('#restart').classList.toggle('hidden',g.phase!=='result'||!(writer||state.owner||ai));$('#chat-form').classList.toggle('hidden',g.mode==='ai'&&state.players.length<2);
 if(writer&&g.phase==='setup')renderSetup(g);if(writer&&g.phase==='addHint')renderExtra(g);renderZones(g,writer);
 if(g.phase==='result')renderResult(g);
}
function renderSetup(g){
 const panel=$('#setup-hints'),data=g.privateData;if(!data)return;
 panel.replaceChildren(...Object.keys(zones).map(zone=>{
  const card=document.createElement('div');card.className='setup-zone';const title=document.createElement('strong');title.textContent=zones[zone];card.append(title);
  for(const type of ['adjective','noun']){
   const key=type==='adjective'?'adjectives':'nouns',sel=document.createElement('select'),placeholder=document.createElement('option');placeholder.value='';placeholder.textContent=type==='adjective'?'형용사 선택':'명사 선택';sel.append(placeholder);
   const elsewhere=new Set(Object.keys(setup).filter(other=>other!==zone).map(other=>setup[other][type]).filter(Boolean));
   for(const word of data.tileSupply[key]){const option=document.createElement('option');option.value=word;option.textContent=word;option.disabled=elsewhere.has(word)&&setup[zone][type]!==word;sel.append(option)}
   sel.value=setup[zone][type]||'';sel.setAttribute('aria-label',zones[zone]+' '+(type==='adjective'?'형용사':'명사'));
   sel.onchange=()=>{setup[zone][type]=sel.value||null;render()};card.append(sel)
  }
  return card
 }));
 const picks=Object.values(setup),complete=picks.every(x=>x.adjective&&x.noun),uniqueA=new Set(picks.map(x=>x.adjective).filter(Boolean)).size===3,uniqueN=new Set(picks.map(x=>x.noun).filter(Boolean)).size===3,ready=complete&&uniqueA&&uniqueN;
 $('#publish-initial').disabled=!ready;$('#setup-feedback').textContent=!complete?'세 영역 모두 형용사 1개와 명사 1개를 선택하세요.':!uniqueA||!uniqueN?'같은 타일은 한 번만 사용할 수 있어요. 다른 타일로 바꿔주세요.':'힌트가 준비됐어요. 버튼을 눌러 수사관에게 공개하세요.';$('#setup-feedback').classList.toggle('is-ready',ready)
}
function renderExtra(g){const supply=g.privateData?.tileSupply;if(!supply)return;$('#drawn-tiles').replaceChildren(...['adjective','noun'].flatMap(tileType=>supply[tileType==='adjective'?'adjectives':'nouns'].map(word=>{const b=document.createElement('button');b.className=`word-tile ${extra.tileType===tileType&&extra.word===word?'selected':''}`;b.textContent=`${tileType==='adjective'?'형용사':'명사'} · ${word}`;b.onclick=()=>{extra={...extra,tileType,word};render()};return b})));$('#zone-targets').replaceChildren(...Object.entries(zones).map(([key,label])=>{const b=document.createElement('button');b.className=`zone-target ${extra.zone===key?'selected':''}`;b.textContent=`${label} ${g.hints[key].length}/4`;b.disabled=g.hints[key].length>=4;b.onclick=()=>{extra.zone=key;render()};return b}));$('#place-hint').disabled=!extra.tileType||!extra.word||!extra.zone||g.hints[extra.zone]?.length>=4}
function renderZones(g,writer){const root=$('#zones'),selectable=['eliminate','final'].includes(g.phase)&&!writer,selected=new Set((g.selected||[]).map(x=>`${x.zone}:${x.id}`));root.replaceChildren(...Object.keys(zones).map(zone=>{const wrap=document.createElement('section');wrap.className='zone';const head=document.createElement('div');head.className='zone-head';const title=document.createElement('strong');title.textContent=zones[zone];const count=document.createElement('span');count.textContent=`${g.hints[zone]?.length||0}개 힌트`;head.append(title,count);const hints=document.createElement('div');hints.className='zone-hints';for(const h of g.hints[zone]||[]){const tile=document.createElement('span');tile.className=`hint-tile ${h.type}`;tile.textContent=h.word;hints.append(tile)}const cards=document.createElement('div');cards.className='cards';for(const c of g.cards[zone].filter(x=>x.active)){const key=`${zone}:${c.id}`,button=document.createElement('button'),isAnswer=writer&&g.privateData?.secret?.[zone]===c.id;button.className=`suspect-card${selected.has(key)?' excluded':''}${isAnswer?' writer-answer-card':''}`;button.textContent=isAnswer?`★ ${c.name} · 정답`:c.name;button.disabled=!selectable;if(selectable)button.onclick=()=>{if(!selected.has(key)&&selected.size>=6){toast('제외 카드는 6장까지만 놓을 수 있어요.');return}send({type:'toggleCard',zone,id:c.id})};cards.append(button)}wrap.append(head,hints,cards);return wrap}));const n=(g.selected||[]).length;$('#selection-count').textContent=`제외 카드 ${n} / 6`;$('#final-count').textContent=`제외 카드 ${n} / 6`;$('#submit-exclusions').disabled=n!==6;$('#submit-final').disabled=n!==6;renderFinalPreview(g,selected)}
function renderFinalPreview(g,selected){const box=$('#final-preview');box.classList.toggle('hidden',g.phase!=='final');if(g.phase!=='final')return;box.replaceChildren();const heading=document.createElement('strong');heading.textContent='제출 후 남을 카드 · 최종 정답 후보';box.append(heading);for(const zone of Object.keys(zones)){const row=document.createElement('p');const survivors=g.cards[zone].filter(card=>card.active&&!selected.has(`${zone}:${card.id}`)).map(card=>card.name);row.textContent=`${zones[zone]}: ${survivors.length?survivors.join(' · '):'없음'}`;box.append(row)}const total=document.createElement('small');total.textContent=`총 ${Object.keys(zones).reduce((sum,zone)=>sum+g.cards[zone].filter(card=>card.active&&!selected.has(`${zone}:${card.id}`)).length,0)}장 남습니다. 정답 세 장을 남기려면 오답 6장을 선택하세요.`;box.append(total)}
function renderResult(g){const box=$('#result-panel');box.replaceChildren();const title=document.createElement('h3');title.textContent=g.message||'사건 종료';const solution=document.createElement('p');solution.textContent=`실제 정답 — ${g.resultSecret?.suspect||'?'} / ${g.resultSecret?.tool||'?'} / ${g.resultSecret?.motive||'?'}`;box.append(title,solution);if(g.resultGuess){const guess=document.createElement('p');guess.className='result-guess';guess.textContent=`플레이어가 남긴 카드 — 용의자: ${g.resultGuess.suspect?.join(', ')||'없음'} / 도구: ${g.resultGuess.tool?.join(', ')||'없음'} / 동기: ${g.resultGuess.motive?.join(', ')||'없음'}`;box.append(guess)}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#join').onclick=()=>connect('online');$('#solo').onclick=()=>connect('ai');for(const id of ['name','code'])$('#'+id).addEventListener('keydown',e=>{if(e.key==='Enter')connect('online')});$('#start-game').onclick=()=>send({type:'startGame'});$('#leave-room').onclick=()=>{if(confirm('현재 방에서 나가 로비로 돌아가시겠어요? 진행 중인 방에서 나가면 다시 입장할 수 없습니다.'))send({type:'leave'})};$('#publish-initial').onclick=()=>{const values=Object.values(setup),ready=values.every(x=>x.adjective&&x.noun)&&new Set(values.map(x=>x.adjective)).size===3&&new Set(values.map(x=>x.noun)).size===3;if(!ready){toast('세 영역에서 서로 다른 형용사와 명사를 하나씩 선택하세요.');return}send({type:'setInitialHints',hints:Object.fromEntries(Object.entries(setup).map(([k,v])=>[k,[{type:'adjective',word:v.adjective},{type:'noun',word:v.noun}]]))})};$('#place-hint').onclick=()=>{send({type:'addHint',tileType:extra.tileType,word:extra.word,zone:extra.zone});extra={tileType:null,word:null,zone:null}};$('#submit-exclusions').onclick=()=>send({type:'eliminate'});$('#submit-final').onclick=()=>send({type:'finalGuess'});$('#restart').onclick=()=>send({type:'newGame'});$('#copy-code').onclick=async()=>{try{await navigator.clipboard.writeText(state.code);toast('방 코드를 복사했어요.')}catch{toast(`방 코드: ${state.code}`)}};$('#chat-form').onsubmit=e=>{e.preventDefault();const input=$('#chat-input');if(input.value.trim())send({type:'chat',text:input.value});input.value=''};
try{const last=JSON.parse(localStorage.getItem('dm-last-session')||'null');if(last?.code&&last?.token){$('#name').value=last.name||'수사관';$('#code').value=last.code;joinInfo={type:last.mode==='ai'?'solo':'join',mode:last.mode,name:last.name,code:last.code,resumeToken:last.token};openSocket()}}catch{}
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
