import { createServer } from 'node:http';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { extname, join, resolve } from 'node:path';
import { createHash, randomBytes, randomInt } from 'node:crypto';
import { WebSocketServer } from 'ws';

const root=process.cwd(),dataDir=resolve(process.env.DATA_DIR||join(root,'.runtime-data')),stateFile=join(dataDir,'rooms.json');
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'};
const PUBLIC_FILES=new Set(['index.html','style.css','app.js','manifest.webmanifest','sw.js','icon.svg']);
const rooms=new Map();let saveTimer=null,saveChain=Promise.resolve();
const tokenHash=token=>createHash('sha256').update(String(token)).digest('hex');
const pick=a=>a[randomInt(a.length)],shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=randomInt(i+1);[b[i],b[j]]=[b[j],b[i]]}return b};
const catalog={suspects:['복서','시인','간호사','경찰관','아이돌','사진작가','요리사','변호사','정원사','마술사','기자','교수','배우','파일럿','화가','탐정','점술가','경비원','사업가','작가','수의사','모델','택시기사'],tools:['화분','가방','휴지통','곰인형','세탁기','냉장고','변기','코트','쇼핑백','우산','액자','전화기','촛대','책','향수','꽃병','스카프','카메라','베개','시계','와인병','청소기','노끈'],motives:['복수','질투','유산','배신','스토킹','강도','비밀','협박','오해'],adjectives:['저렴한','예술적인','답답한','무거운','차가운','화려한','수상한','조용한','낡은','달콤한','위험한','외로운','반짝이는','젖은','익숙한','불편한','완벽한','어두운','가벼운','따뜻한','급한','슬픈','기묘한','평범한','끈적한','날카로운','고요한','부서진','새로운','텅 빈','강렬한','느린','비밀스러운','부드러운','거대한','작은','붉은','푸른','어지러운','행복한','미끄러운','단단한','흐릿한','시끄러운','비싼'],nouns:['몸','접촉','생활','손','눈','소리','냄새','기억','관계','흔적','방문','약속','장난','대화','거리','시간','선물','그림','문','열쇠','침묵','거짓말','습관','취미','여행','식사','옷','얼굴','편지','사진','불빛','그림자','꿈','비','음악','유리','잠','춤','말','마음','이름','벽','온도','맛','소문']};
const aiPhrases={suspect:{'복서':['강렬한','손'],'시인':['예술적인','말'],'간호사':['따뜻한','몸'],'경찰관':['수상한','흔적'],'아이돌':['화려한','소리'],'사진작가':['흐릿한','기억'],'요리사':['달콤한','맛'],'변호사':['날카로운','말'],'정원사':['젖은','나무'],'마술사':['기묘한','장난'],'기자':['급한','소문'],'교수':['조용한','기억'],'배우':['강렬한','얼굴'],'파일럿':['외로운','여행'],'화가':['예술적인','그림'],'탐정':['수상한','흔적'],'점술가':['어두운','꿈'],'경비원':['무거운','문'],'사업가':['비싼','선물'],'작가':['외로운','편지'],'수의사':['따뜻한','몸'],'모델':['화려한','얼굴'],'택시기사':['느린','거리']},tool:{'화분':['젖은','나무'],'가방':['가벼운','여행'],'휴지통':['낡은','생활'],'곰인형':['외로운','선물'],'세탁기':['젖은','옷'],'냉장고':['차가운','식사'],'변기':['답답한','생활'],'코트':['차가운','옷'],'쇼핑백':['비싼','선물'],'우산':['젖은','비'],'액자':['흐릿한','기억'],'전화기':['급한','소리'],'촛대':['어두운','불빛'],'책':['조용한','말'],'향수':['익숙한','냄새'],'꽃병':['예술적인','꽃'],'스카프':['부드러운','옷'],'카메라':['흐릿한','그림'],'베개':['부드러운','잠'],'시계':['급한','시간'],'와인병':['달콤한','식사'],'청소기':['시끄러운','생활'],'노끈':['단단한','손']},motive:{'복수':['날카로운','기억'],'질투':['어두운','관계'],'유산':['비싼','선물'],'배신':['차가운','약속'],'스토킹':['수상한','거리'],'강도':['가벼운','가방'],'비밀':['비밀스러운','말'],'협박':['답답한','소리'],'오해':['흐릿한','말']}};
const aiPhrase=(zone,name)=>aiPhrases[zone][name]||['수상한','흔적'];
const server=createServer(async(req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('X-Frame-Options','DENY');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' ws: wss:; manifest-src 'self'; worker-src 'self'");if(pathname==='/healthz'){res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify({ok:true,rooms:rooms.size}));return}const name=pathname==='/'?'index.html':pathname.slice(1);if(!PUBLIC_FILES.has(name)){res.writeHead(404).end('Not found');return}try{const body=await readFile(join(root,name));res.writeHead(200,{'Content-Type':MIME[extname(name)]||'application/octet-stream','Cache-Control':name==='index.html'?'no-cache':'public, max-age=300'}).end(body)}catch{res.writeHead(404).end('Not found')}});
const wss=new WebSocketServer({noServer:true,maxPayload:16*1024,perMessageDeflate:false});
server.on('upgrade',(req,socket,head)=>{try{const url=new URL(req.url,'http://localhost'),origin=req.headers.origin;if(url.pathname!=='/room'||origin&&new URL(origin).host!==req.headers.host){socket.write('HTTP/1.1 403 Forbidden\r\n\r\n');socket.destroy();return}wss.handleUpgrade(req,socket,head,ws=>wss.emit('connection',ws,req))}catch{socket.destroy()}});
async function loadState(){try{const saved=JSON.parse(await readFile(stateFile,'utf8'));for(const r of saved){if(!r||typeof r.code!=='string'||!Array.isArray(r.players)||r.players.length>6)continue;rooms.set(r.code,{code:r.code,mode:r.mode||'online',ownerId:r.ownerId||r.players[0]?.id,createdAt:r.createdAt||Date.now(),players:new Map(r.players.map(p=>[p.id,{...p,connected:false}])),sockets:new Set(),game:r.game||null})}}catch(e){if(e.code!=='ENOENT')console.error('Could not restore saved rooms:',e.message)}}
function persistNow(){const serial=[...rooms.values()].map(r=>({code:r.code,mode:r.mode,ownerId:r.ownerId,createdAt:r.createdAt,players:[...r.players.values()].map(p=>({...p,connected:false})),game:r.game}));saveChain=saveChain.then(async()=>{await mkdir(dataDir,{recursive:true});await writeFile(`${stateFile}.tmp`,JSON.stringify(serial));await rename(`${stateFile}.tmp`,stateFile)}).catch(e=>console.error('Could not persist rooms:',e.message));return saveChain}
function saveSoon(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>persistNow(),120)}
await loadState();
const send=(ws,message)=>{if(ws.readyState===1)ws.send(JSON.stringify(message))};
function publicRoom(room,viewer){const g=room.game;return{code:room.code,mode:room.mode,owner:room.ownerId===viewer,players:[...room.players.values()].map(p=>({id:p.id,name:p.name,role:p.role,connected:!!p.connected})),game:g?{mode:g.mode,phase:g.phase,round:g.round,lives:g.lives,privateRole:g.writer===viewer?'writer':g.writer==='AI'?'ai':'investigator',cards:g.cards,hints:g.hints,selected:g.selected,choices:{adjectives:catalog.adjectives,nouns:catalog.nouns},privateData:g.writer===viewer?{secret:g.secret,tileSupply:g.tileSupply}:null,resultSecret:g.phase==='result'?{suspect:catalog.suspects[g.secret.suspect],tool:catalog.tools[g.secret.tool],motive:catalog.motives[g.secret.motive]}:null,resultGuess:g.phase==='result'?g.lastGuess||null:null,message:g.message}:null}}
function broadcast(room){for(const ws of room.sockets)send(ws,{type:'state',state:publicRoom(room,ws.id)});saveSoon()}
function notice(room,text){room.game.message=text;broadcast(room);for(const ws of room.sockets)send(ws,{type:'notice',message:text})}
function uniqueNine(list){return shuffle(list).slice(0,9).map((name,id)=>({id,name,active:true}))}
function newGame(room,mode='online'){const ids=shuffle([...room.players.keys()]),writer=mode==='ai'?'AI':ids[0],cards={suspect:uniqueNine(catalog.suspects),tool:uniqueNine(catalog.tools),motive:uniqueNine(catalog.motives)},secret={suspect:randomInt(9),tool:randomInt(9),motive:randomInt(9)};let adjectiveBag=shuffle(catalog.adjectives),nounBag=shuffle(catalog.nouns),adjectives=adjectiveBag.splice(0,6),nouns=nounBag.splice(0,6);if(mode==='ai'){const required=Object.keys(cards).map(zone=>aiPhrase(zone,cards[zone][secret[zone]].name)),reqA=[...new Set(required.map(x=>x[0]))],reqN=[...new Set(required.map(x=>x[1]))];adjectives=[...reqA,...shuffle(catalog.adjectives.filter(x=>!reqA.includes(x))).slice(0,6-reqA.length)];nouns=[...reqN,...shuffle(catalog.nouns.filter(x=>!reqN.includes(x))).slice(0,6-reqN.length)];adjectiveBag=shuffle(catalog.adjectives.filter(x=>!adjectives.includes(x)));nounBag=shuffle(catalog.nouns.filter(x=>!nouns.includes(x)))}room.game={mode,phase:'setup',round:1,writer,cards,secret,lives:4,hints:{suspect:[],tool:[],motive:[]},tileSupply:{adjectives,nouns},tileBags:{adjectives:adjectiveBag,nouns:nounBag},message:null,selected:[],lastGuess:null};for(const id of ids)room.players.get(id).role=id===writer?'writer':'investigator';if(mode==='ai'){for(const zone of Object.keys(cards)){const[a,n]=aiPhrase(zone,cards[zone][secret[zone]].name);room.game.hints[zone]=[{type:'adjective',word:a},{type:'noun',word:n}];room.game.tileSupply.adjectives=room.game.tileSupply.adjectives.filter(x=>x!==a);room.game.tileSupply.nouns=room.game.tileSupply.nouns.filter(x=>x!==n)}room.game.phase='eliminate'}room.createdAt=Date.now();broadcast(room)}
function makeCode(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let code;do{code=Array.from({length:5},()=>alphabet[randomInt(alphabet.length)]).join('')}while(rooms.has(code));return code}
function aiDropHint(room){const g=room.game;for(const type of ['adjectives','nouns'])if(g.tileBags[type].length)g.tileSupply[type].push(g.tileBags[type].pop());const zone=shuffle(['suspect','tool','motive']).find(z=>g.hints[z].length<4);if(!zone)return;const type=pick(['adjective','noun']),key=type==='adjective'?'adjectives':'nouns',word=pick(g.tileSupply[key]);if(word){g.hints[zone].push({type,word});g.tileSupply[key]=g.tileSupply[key].filter(x=>x!==word)}}
const activeCards=g=>Object.fromEntries(Object.entries(g.cards).map(([k,v])=>[k,v.filter(c=>c.active)]));
function handle(room,ws,m){const g=room.game,p=room.players.get(ws.id);if(!p)return;if(m.type==='leave'){const leavingId=ws.id;room.sockets.delete(ws);room.players.delete(leavingId);if(room.ownerId===leavingId)room.ownerId=room.players.keys().next().value||null;if(g&&room.mode==='online'&&g.writer===leavingId&&g.phase!=='result'){g.phase='result';g.selected=[];g.message='소설가가 방을 나가 사건이 종료되었습니다. 방장이 새 사건을 시작할 수 있습니다.'}ws.room=null;ws.id=null;send(ws,{type:'left'});ws.close(1000,'left room');if(room.players.size)broadcast(room);else rooms.delete(room.code);saveSoon();return}const writer=g&&ws.id===g.writer;
 if(m.type==='toggleCard'&&g&&['eliminate','final'].includes(g.phase)&&!writer){const zone=m.zone,id=Number(m.id),card=g.cards[zone]?.find(c=>c.id===id&&c.active);if(!card)return;const i=g.selected.findIndex(x=>x.zone===zone&&x.id===id);if(i>=0)g.selected.splice(i,1);else if(g.selected.length<6)g.selected.push({zone,id});else{send(ws,{type:'notice',message:'제외 카드는 6장까지만 놓을 수 있습니다.'});return}broadcast(room);return}
 if(m.type==='startGame'&&!g&&ws.id===room.ownerId&&(room.mode==='ai'?room.players.size>=1:room.players.size>=2)){newGame(room,room.mode==='ai'?'ai':'online');return}
 if(!g)return;
 if(m.type==='setInitialHints'&&g.phase==='setup'&&writer){const submitted=m.hints;if(!submitted||!['suspect','tool','motive'].every(z=>Array.isArray(submitted[z])&&submitted[z].length===2))return;const usedA=[],usedN=[],valid=[];for(const z of ['suspect','tool','motive']){const pair=submitted[z];if(pair.filter(x=>x?.type==='adjective').length!==1||pair.filter(x=>x?.type==='noun').length!==1)return;for(const x of pair){if(x.type==='adjective'&&!g.tileSupply.adjectives.includes(x.word)||x.type==='noun'&&!g.tileSupply.nouns.includes(x.word))return;(x.type==='adjective'?usedA:usedN).push(x.word)}valid.push([z,pair])}if(new Set(usedA).size!==3||new Set(usedN).size!==3)return;for(const x of usedA)g.tileSupply.adjectives=g.tileSupply.adjectives.filter(y=>y!==x);for(const x of usedN)g.tileSupply.nouns=g.tileSupply.nouns.filter(y=>y!==x);for(const[z,pair]of valid)g.hints[z]=pair;g.phase='eliminate';g.message='초기 힌트가 놓였습니다. 정답이 아닌 카드 6장을 함께 골라주세요.';broadcast(room);return}
 if(m.type==='eliminate'&&g.phase==='eliminate'&&!writer){const selected=g.selected;if(selected.length!==6)return;const fail=selected.some(x=>g.secret[x.zone]===x.id);g.selected=[];if(fail){g.lives--;g.message=g.lives?'추리 실패! 정답 위치는 공개되지 않습니다. 카드 6장을 다시 골라주세요.':'추리 타일을 모두 사용했습니다. 사건 해결에 실패했습니다.';if(!g.lives)g.phase='result';broadcast(room);return}for(const x of selected)g.cards[x.zone].find(c=>c.id===x.id).active=false;if(g.round===3){g.phase='final';g.message='3라운드 성공! 남은 카드에서 정답 3장만 남기고 나머지 6장을 제외하세요.'}else{g.round++;if(g.mode==='ai'){aiDropHint(room);g.phase='eliminate';g.message=`${g.round}라운드 힌트가 추가됐습니다.`}else{for(const type of ['adjectives','nouns'])if(g.tileBags[type].length)g.tileSupply[type].push(g.tileBags[type].pop());g.phase='addHint';g.message=`${g.round}라운드입니다. 소설가는 보유 타일 중 하나를 원하는 영역에 추가하세요.`}}broadcast(room);return}
 if(m.type==='addHint'&&g.phase==='addHint'&&writer){const type=m.tileType,word=m.word,zone=m.zone,key=type==='adjective'?'adjectives':'nouns';if(!['adjective','noun'].includes(type)||!['suspect','tool','motive'].includes(zone)||!g.tileSupply[key].includes(word)||g.hints[zone].length>=4)return;g.hints[zone].push({type,word});g.tileSupply[key]=g.tileSupply[key].filter(x=>x!==word);g.phase='eliminate';g.message='힌트가 추가됐습니다. 정답이 아닌 카드 6장을 함께 골라주세요.';broadcast(room);return}
 if(m.type==='finalGuess'&&g.phase==='final'&&!writer){const remain=activeCards(g),remainingCount=Object.values(remain).reduce((sum,cards)=>sum+cards.length,0);if(g.selected.length!==6||remainingCount!==9)return;const excluded=new Set(g.selected.map(x=>`${x.zone}:${x.id}`));const left=Object.fromEntries(Object.keys(remain).map(z=>[z,remain[z].filter(c=>!excluded.has(`${z}:${c.id}`))]));const leftCount=Object.values(left).reduce((sum,cards)=>sum+cards.length,0);const answersSafe=Object.keys(g.secret).every(zone=>!excluded.has(`${zone}:${g.secret[zone]}`));const success=leftCount===3&&answersSafe;g.lastGuess=Object.fromEntries(Object.keys(left).map(zone=>[zone,left[zone].map(card=>card.name)]));g.selected=[];if(success){g.phase='result';g.message='정답입니다! 남긴 카드 3장이 정답과 일치합니다. 모두 함께 사건을 해결했습니다.'}else{g.lives--;g.message=g.lives?`최종 추리 실패! 추리 타일 ${g.lives}개가 남았습니다. 남긴 카드와 정답을 다시 확인하세요.`:'추리 타일을 모두 사용했습니다. 사건 해결에 실패했습니다.';if(!g.lives)g.phase='result'}broadcast(room);return}
 if(m.type==='newGame'&&g.phase==='result'&&(writer||room.ownerId===ws.id)){newGame(room,g.mode);return}
 if(m.type==='chat'&&(room.mode==='online'||room.mode==='ai'&&room.players.size>1)){const text=String(m.text||'').trim().slice(0,180);if(text)for(const s of room.sockets)send(s,{type:'chat',name:p.name,text})}
}
function attach(ws,room,player,token){ws.room=room;ws.id=player.id;room.sockets.add(ws);player.connected=true;player.resumeUntil=Date.now()+24*60*60*1000;player.tokenHash=tokenHash(token);for(const old of room.sockets)if(old!==ws&&old.id===ws.id)old.close(4001,'Reconnected');send(ws,{type:'welcome',id:player.id,code:room.code,mode:room.mode,owner:player.id===room.ownerId});broadcast(room)}
function createRoom(code,mode){return{code,mode,ownerId:null,createdAt:Date.now(),players:new Map(),sockets:new Set(),game:null}}
wss.on('connection',ws=>{ws._rateStart=Date.now();ws._rateCount=0;ws.on('message',raw=>{if(Date.now()-ws._rateStart>1000){ws._rateStart=Date.now();ws._rateCount=0}if(++ws._rateCount>40){ws.close(1008,'Rate limit');return}let m;try{m=JSON.parse(raw)}catch{send(ws,{type:'error',message:'잘못된 메시지입니다.'});return}if(!m||typeof m!=='object')return;
 if(m.type==='join'||m.type==='solo'){const requestedMode=m.type==='solo'?'ai':'online',name=String(m.name||'수사관').trim().slice(0,16)||'수사관',token=String(m.resumeToken||'');if(token.length<32){send(ws,{type:'error',message:'안전한 재접속 토큰을 만들 수 없습니다. 다시 시도해 주세요.'});return}let code=requestedMode==='ai'?String(m.code||''):String(m.code||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,5);if(!code)code=makeCode();let room=rooms.get(code);if(!room){room=createRoom(code,requestedMode);rooms.set(code,room)}const mode=room.mode;if(!['ai','online'].includes(mode)){send(ws,{type:'error',message:'알 수 없는 게임 모드입니다.'});return}let player=[...room.players.values()].find(x=>x.tokenHash===tokenHash(token));if(!player){if(room.game&&room.game.phase!=='result'){send(ws,{type:'error',message:'이미 시작된 방에는 새로 입장할 수 없습니다.'});return}if(room.players.size>=6){send(ws,{type:'error',message:'방은 최대 6명까지 참가할 수 있습니다.'});return}player={id:randomBytes(12).toString('hex'),name,role:'investigator',tokenHash:tokenHash(token),connected:false,resumeUntil:Date.now()+24*60*60*1000};room.players.set(player.id,player);if(!room.ownerId)room.ownerId=player.id}else player.name=name;attach(ws,room,player,token);saveSoon();return}
 if(ws.room)handle(ws.room,ws,m);
 });ws.on('close',()=>{const room=ws.room,player=room?.players.get(ws.id);if(!room||!player)return;room.sockets.delete(ws);if(![...room.sockets].some(other=>other.id===ws.id&&other.readyState===1)){player.connected=false;player.resumeUntil=Date.now()+24*60*60*1000;broadcast(room)} });});
setInterval(()=>{const now=Date.now();for(const room of rooms.values()){for(const[id,p]of room.players)if(!p.connected&&p.resumeUntil&&p.resumeUntil<now)room.players.delete(id);if(!room.players.size){rooms.delete(room.code);continue}if(room.ownerId&&!room.players.has(room.ownerId))room.ownerId=room.players.keys().next().value||null}saveSoon()},60_000).unref();
const port=Number(process.env.PORT)||3000;server.listen(port,'0.0.0.0',()=>console.log(`Dying Message running on port ${port}; persistent room data: ${dataDir}`));
async function shutdown(){clearTimeout(saveTimer);await persistNow();server.close(()=>process.exit(0));setTimeout(()=>process.exit(0),5000).unref()}
process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
